//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DONHANG
    {
        public int MADH { get; set; }
        public int MASP { get; set; }
        public int SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
