//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public DANHMUC()
        {
            this.SANPHAM = new HashSet<SANPHAM>();
        }
    
        public string MADANHMUC { get; set; }
        public string TENDANHMUC { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAM { get; set; }
    }
}
