//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public DONHANG()
        {
            this.CT_DONHANG = new HashSet<CT_DONHANG>();
            this.GIAODICH = new HashSet<GIAODICH>();
        }
    
        public int MADH { get; set; }
        public int MAND { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public string DIACHI_GIAO { get; set; }
        public decimal TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<CT_DONHANG> CT_DONHANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual ICollection<GIAODICH> GIAODICH { get; set; }
    }
}
