//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public GIOHANG()
        {
            this.CT_GIOHANG = new HashSet<CT_GIOHANG>();
        }
    
        public int MAGH { get; set; }
        public int MAND { get; set; }
        public System.DateTime NGAYCAPNHAT { get; set; }
    
        public virtual ICollection<CT_GIOHANG> CT_GIOHANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
