//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public int MAGD { get; set; }
        public int MADH { get; set; }
        public string PHUONGTHUC { get; set; }
        public decimal SOTIEN { get; set; }
        public string TRANGTHAI { get; set; }
        public System.DateTime NGAYGD { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
