//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.DONHANG = new HashSet<DONHANG>();
            this.GIOHANG = new HashSet<GIOHANG>();
        }
    
        public int MAND { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string MATKHAU { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string VAITRO { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        public virtual ICollection<DONHANG> DONHANG { get; set; }
        public virtual ICollection<GIOHANG> GIOHANG { get; set; }
    }
}
