//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CT_DONHANG = new HashSet<CT_DONHANG>();
            this.CT_GIOHANG = new HashSet<CT_GIOHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public decimal GIABAN { get; set; }
        public string HINHANH { get; set; }
        public string MADM { get; set; }
        public int MATH { get; set; }
        public int SOLUONG { get; set; }
        public decimal KHUYENMAI { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<CT_DONHANG> CT_DONHANG { get; set; }
        public virtual ICollection<CT_GIOHANG> CT_GIOHANG { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
